<a href="https://colab.research.google.com/github/Shrivastav-Gaurav/GenAI-ML-Notebook/blob/main/Introduction_to_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What is a Tensor?



A tensor is a generalization of vectors and matrices to potentially higher dimensions, see the Table below. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes. Each element in the Tensor has the same data type, and the data type is always known. Simply, tensor, in relation to machine learning, is a generalization of scalars, vectors and, matrices.
<br><br>
<center>
<img src= "https://cdn.iisc.talentsprint.com/AIandMLOps/Images/Intro_tensor.png" width=700px/>
</center>

### Install Library

In [ ]:
!pip install torch

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 43.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 39.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 29.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 10.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 6.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 69.7 MB/s eta 0:00:00
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlin

## Creation

In [ ]:
import torch

### 1. Direct Creation

In [ ]:
tensor = torch.tensor([1, 2, 3])
print(tensor)

tensor([1, 2, 3])


#### Using `torch.zeros()`

In [ ]:
tensor_zeros = torch.zeros(3)
print(tensor_zeros)

tensor([0., 0., 0.])


#### Using `torch.ones()`

In [ ]:
tensor_ones = torch.ones(2, 3)
print(tensor_ones)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


#### Using `torch.empty()`

In [ ]:
tensor_empty = torch.empty(2, 3)
print(tensor_empty)

tensor([[-7.2012e+29,  4.5827e-41,  6.2425e+01],
        [ 0.0000e+00,  4.4842e-44,  0.0000e+00]])


### 2. Random Initialization

#### Using `torch.randn()`

In [ ]:
tensor_norm_distribution = torch.randn(4, 4, 4)
print(tensor_norm_distribution)


tensor([[[-0.7516,  0.1403, -0.4128,  1.2203],
         [-0.8997,  3.2778, -1.6432, -0.7858],
         [ 1.3337,  1.0487,  0.3911,  1.2901],
         [-0.4301, -0.1966, -2.4229,  0.2107]],

        [[ 2.1888,  0.4934, -1.1037, -0.3060],
         [ 0.1497,  0.3080,  1.0626, -1.2945],
         [ 0.2286,  0.1839,  0.5812, -0.7024],
         [-0.3857,  0.4114,  0.4473, -0.7705]],

        [[ 0.6688, -2.2977, -0.7570,  0.2519],
         [-1.3559,  0.1091,  0.2178, -0.2534],
         [-0.9192,  1.1407, -0.1968,  0.8856],
         [-0.2057,  0.0892,  0.8038, -1.3935]],

        [[ 0.6986, -0.9948, -1.1566, -0.4969],
         [-0.5618,  1.2492,  0.5253, -1.1294],
         [-0.9022,  1.5705, -0.9793, -0.6969],
         [ 1.1388, -0.1342, -0.1914,  0.4428]]])


#### Using `torch.rand()`

In [ ]:
tensor_uniform_distribution = torch.rand(4, 4)
print(tensor_uniform_distribution)

tensor([[0.9987, 0.1424, 0.2751, 0.9243],
        [0.3145, 0.0495, 0.8667, 0.6560],
        [0.3834, 0.1183, 0.8890, 0.8559],
        [0.7170, 0.4941, 0.3480, 0.1848]])


### 3. Specific initialization:

#### Using `torch.arange()`

In [ ]:
tensor_arange = torch.arange(0, 10, 2)
print(tensor_arange)

tensor([0, 2, 4, 6, 8])


#### Using `torch.linspace()`

In [ ]:
tensor_linspace = torch.linspace(0, 1, 5)
print(tensor_linspace)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])



#### Using `torch.eye()`

In [ ]:
tensor_eye = torch.eye(3)
print(tensor_eye)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [ ]:
import torch
# Create a 3-dimensional tensor with random values from a uniform distribution
random_tensor = torch.rand(2, 3, 4)
print(random_tensor)

tensor([[[0.2660, 0.8240, 0.8665, 0.2096],
         [0.4942, 0.6521, 0.7722, 0.8110],
         [0.0438, 0.2807, 0.4389, 0.8550]],

        [[0.6957, 0.5408, 0.4197, 0.2850],
         [0.3908, 0.4801, 0.9678, 0.7021],
         [0.3388, 0.2887, 0.9778, 0.3098]]])


### 4. Other methods

#### Using `torch.from_numpy()`

In [ ]:
import numpy as np

np_array = np.array([1, 2, 3])
tensor_from_np = torch.from_numpy(np_array)
print(tensor_from_np)

tensor([1, 2, 3])


#### Using `torch.load()`

In [ ]:
tensor = torch.randn(2, 3)
torch.save(tensor, 'tensor.pt')

In [ ]:
# weights_only: Indicates whether unpickler should be restricted to loading only tensors, primitive types, dictionaries
tensor_loaded = torch.load('tensor.pt', weights_only=False) # fixes future warning
print(tensor_loaded)

tensor([[-0.5212, -1.1785,  1.3157],
        [-1.1839, -1.9914, -0.2608]])


## Basic Mathematical Operations on Tensors





💥 Addition: Adds corresponding elements of tensors together, allowing for combining information or increasing values.

💥 Subtraction: Subtracts corresponding elements of tensors, useful for computing differences or detecting changes.

💥 Multiplication: Performs element-wise multiplication of tensors, enabling scaling or emphasizing certain features.
To perform matrix like multiplication of tensors: torch.matmul(tensor1, tensor2)

💥 Division: Divides corresponding elements of tensors, useful for normalization or finding relative proportions.

In [ ]:
import torch
# Create a base tensor
base_tensor = torch.tensor ([[1, 2], [3,4]])
# Create another tensor
second_tensor = torch.tensor ([[2, 2], [1,1]])
# Addition
addition_tensor = base_tensor + second_tensor
print("Addition: \\n", addition_tensor)
# Subtraction
subtraction_tensor = base_tensor - second_tensor
print("Subtraction: \\n", subtraction_tensor)
# Multiplication
multiplication_tensor = base_tensor * second_tensor
print("Multiplication: \\n", multiplication_tensor)
# Division
division_tensor = base_tensor / second_tensor
print("Division: In", division_tensor)


Addition: \n tensor([[3, 4],
        [4, 5]])
Subtraction: \n tensor([[-1,  0],
        [ 2,  3]])
Multiplication: \n tensor([[2, 4],
        [3, 4]])
Division: In tensor([[0.5000, 1.0000],
        [3.0000, 4.0000]])


## Tensor indexing and slicing  


`::` in tensor slicing in PyTorch (or NumPy) is used to specify a step size.

When you use `::` within square brackets when indexing a tensor, you're essentially telling Python to select elements from the tensor at regular intervals.

### **Breakdown:**

1. First `:` Indicates the starting index (usually 0 if omitted).
1. Second `:` Indicates the ending index (usually the end of the tensor if omitted).
1. `:` Specifies the step size.

1-D Tensor Example

In [ ]:
import torch

tensor = torch.tensor([1, 2, 3, 4, 5])

# Extract every other element
subtensor = tensor[::2]  # Output: tensor([1, 3, 5])

# Extract elements starting from the 2nd index, every 3rd element
subtensor = tensor[1::3]  # Output: tensor([2, 5])

Multi-Dimension Example

In [ ]:
import torch
# Create a 3-D tensor with size (2, 3, 3)
tensor = torch.tensor ([
	[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
	[[10, 11, 12], [13, 14, 15],[16, 17,18]]
])
print ("Original Tensor:")
print (tensor, end='\n\n')
print("Tensor Shape:", tensor.shape)


Original Tensor:
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

Tensor Shape: torch.Size([2, 3, 3])


Understanding the shape of a tensor is essential for working with PyTorch.  

Here we have:  

1. 2 outer elements/batches/samples. The number of independent data pointsUnd
1. Each outer element is a `3x3` matrix (`3 rows, 3 columns`)

To make it easy to mentally visualize this tensor, you can imagine it as two stacked `3x3` matrices:

```
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[10, 11, 12], [13, 14, 15], [16, 17, 18]]
```



### **Row Slice (Slice of the second row)**

This expression extracts a slice of the tensor that consists of all elements in the second row of each 3x3 matrix within the tensor.  

Using `tensor[:, 1, :]`

1. First `:` means keep all elements along first dimension i.e. the outer dimension.  

1. 1 means we want to select the second element along the second dimension i.e. the rows

1. Last `:` means that we want all elements along the third dimension i.e. the columns

In [ ]:
# Row Slice (Slice of the second row)
row_slice = tensor[:, 1, :]
print("\\now Slice:")
print (row_slice)
print ("Row Slice Shape:", row_slice.shape)

\now Slice:
tensor([[ 4,  5,  6],
        [13, 14, 15]])
Row Slice Shape: torch.Size([2, 3])


The resulting tensor has two rows (corresponding to the two outer elements) and three columns (corresponding to the elements in the second row of each matrix).

### **Column Slice (Slice of the third column)**

In [ ]:
# Column Slice (Slice of the third column)
column_slice = tensor[:,:, 2]
print ("\\nColumn Slice:")
print(column_slice)
print ("Column Slice Shape:", column_slice.shape)


\nColumn Slice:
tensor([[ 3,  6,  9],
        [12, 15, 18]])
Column Slice Shape: torch.Size([2, 3])


### **Mixed Slice**

In [ ]:
# Mixed Slice (Mixed slice of rows and columns)
mixed_slice = tensor[:, 0:2, 1:3]
print("\\nMixed Slice:")
print (mixed_slice)
print("Mixed Slice Shape:", mixed_slice.shape)



\nMixed Slice:
tensor([[[ 2,  3],
         [ 5,  6]],

        [[11, 12],
         [14, 15]]])
Mixed Slice Shape: torch.Size([2, 2, 2])


## **Reshaping and View in Tensors**

In [ ]:
# Create a contiguous 2D tensor
tensor = torch.tensor([
	[1, 2, 3],
	[4, 5, 6]
])
# Reshape the tensor using view
reshaped_tensor = tensor.view(3, 2)
print("Original Tensor:")
print (tensor)
print ("\\nReshaped Tensor:")
print (reshaped_tensor)



Original Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])
\nReshaped Tensor:
tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [ ]:
import torch
# Create a non-contiguous 2D tensor using slicing
tensor = torch. tensor([[1, 2, 3, 4, 5, 6]])
sliced_tensor = tensor[:, :3]
# Reshape the tensor using reshape
reshaped_tensor = torch.reshape(sliced_tensor, (1, 3))
print ("Original Tensor:")
print (sliced_tensor)
print("\\nReshaped Tensor:")
print (reshaped_tensor)



Original Tensor:
tensor([[1, 2, 3]])
\nReshaped Tensor:
tensor([[1, 2, 3]])


## **The `-1` trick in `view()`.**
Automatic inference of dimensions.


In [ ]:
import torch
# Create a tensor with size (2, 4)
tensor = torch. tensor([
	[1, 2, 3, 4],
	[5, 6, 7, 8]
])
# Reshape the tensor using view and -1 trick
reshaped_tensor = tensor.view(-1, 2)
print("Original Tensor:")
print (tensor)
print ("\\nReshaped Tensor:")
print (reshaped_tensor)


Original Tensor:
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
\nReshaped Tensor:
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


### **Breakdown:**

1. `tensor`: This refers to the original tensor you want to reshape.
1. `view(-1, 2)`: This specifies the new shape:
  - `-1`: Indicates that the first dimension should be inferred automatically.
  - `2`: Specifies that the second dimension should be 2.  

PyTorch calculates the total number of elements in the original tensor.
It then determines the appropriate value for the first dimension `(-1)` based on the total number of elements and the desired second dimension of 2.
The tensor is then reshaped accordingly, preserving the total number of elements.

In [ ]:
a= torch.ones(2,3,4)
b= a.view(1,4,-1)
print(b.shape)

torch.Size([1, 4, 6])


## **Gradient calculation with Tensors**

In [ ]:
import torch
# Enable gradient tracking
x = torch.tensor(3.0, requires_grad=True)

# Perform operations on the tensor
z = x ** 2 + 1

# Compute gradients
z.backward()

# Access the computed gradients
x_grad = x.grad

print(x_grad)

tensor(6.)


## **Detaching and `no_grad()`**.

`detach()`  

- **Purpose:** Creates a new tensor that shares the same storage as the original tensor but is detached from its computational graph.  

- **Effect:** When you call `detach()` on a tensor, it effectively breaks the connection between that tensor and the computational graph. This means that subsequent operations on the detached tensor will not contribute to the gradient calculation.

In [ ]:
import torch

x = torch.randn(3, 3, requires_grad=True)
y = x.detach()

# Operations on y will not affect the gradient of x
z = y * 2

try:
    z.backward()  # This will raise an error because y is detached
except RuntimeError as e:
    print("Error:", e)
print(f'Gradients of x: {x.grad}')  # Output: None

Error: element 0 of tensors does not require grad and does not have a grad_fn
Gradients of x: None


`no_grad()`
- **Purpose:** Creates a context manager that temporarily disables automatic gradient calculation for all operations within its scope.
- **Effect:** When you use the `no_grad()` context manager, any operations performed within its block will not contribute to the gradient calculation. This can be useful for performance optimization or when you want to evaluate a model without updating its parameters.


In [ ]:
import torch

# Create a tensor with tracking enabled
x = torch.tensor([3.0], requires_grad=True)

# Perform operations on the tensor
y = x**2 + 2*x + 1
print(f'y: {y}')

# Stop tracking gradients using detach()
# Detach the tensor from the computational graph
z = y.detach()
print(f'z: {z}')


# Perform further operations without tracking
with torch.no_grad() :
  w = z * 2
print(f'w: {w}')

y: tensor([16.], grad_fn=<AddBackward0>)
z: tensor([16.])
w: tensor([32.])


In [ ]:
with torch.no_grad():
    x = torch.randn(3, 3, requires_grad=True)
    y = x * 2
    z = y.sum()

# Operations on x, y, and z within the context manager did not contribute to gradients
print(f'x: {x}')
print(f'y: {y}')
print(f'z: {z}', end='\n\n')

print(f'Gradients of x: {x.grad}')  # Output: None


x: tensor([[ 1.1375,  1.1863, -0.9315],
        [-0.1975, -0.3978, -0.5008],
        [-0.4273, -1.4600,  0.1484]], requires_grad=True)
y: tensor([[ 2.2750,  2.3726, -1.8631],
        [-0.3950, -0.7955, -1.0017],
        [-0.8545, -2.9199,  0.2967]])
z: -2.885369300842285

Gradients of x: None


## Tensors in Neural Net
### **Weighted Sum Computation**
The mathematical operation for calculating the weighted sum in a neural network is essentially a matrix multiplication followed by vector addition.

In [ ]:
import torch

# Define input, weights, and bias tensors
input_tensor = torch.randn(4, 3)  # 4 samples, 3 features
weights_tensor = torch.randn(3, 5)  # 3 input features, 5 output features
bias_tensor = torch.randn(5)  # 5 output features

# Calculate weighted sum
weighted_sum = torch.matmul(input_tensor, weights_tensor) + bias_tensor

# Apply activation function (e.g., ReLU)
output_tensor = torch.relu(weighted_sum)

print(output_tensor.shape)  # Output: torch.Size([4, 5])

torch.Size([4, 5])



1. **Input tensor:** A `4x3` tensor representing 4 samples with 3 features each.
1. **Weights tensor:** A `3x5` tensor representing the weights for a fully connected layer with 3 input neurons and 5 output neurons.
1. **Bias tensor:** A 1D tensor with 5 elements, representing the biases for each output neuron.
1. **Weighted sum:** The input tensor is multiplied by the weights tensor, and the bias tensor is added to the result.
1. **Output tensor:** The weighted sum is passed through the ReLU activation function to produce the final output.
The output tensor will have a shape of (4, 5), indicating that for each of the 4 input samples, the neural network produces 5 output values.

### **Numpy's Efficiency and Advantages over Lists**

Numpy's superior performance compared to Python lists stems from several key factors:

1. **Memory Efficiency:**
   - Numpy arrays are stored in **contiguous memory blocks**, allowing for efficient access and manipulation.
   - Python lists, on the other hand, store elements as pointers to objects, leading to overhead in memory allocation and retrieval.

2. **Vectorized Operations:**
   - Numpy provides vectorized operations that perform operations on entire arrays at once, avoiding the need for explicit loops.
   - This significantly improves performance, especially for large datasets.

3. **C/C++ Implementation:**
   - Numpy is implemented in C and Fortran, which are much faster than Python.
   - This allows for efficient execution of numerical computations.

4. **Optimized Algorithms:**
   - Numpy leverages highly optimized algorithms for common mathematical operations, further enhancing performance.

5. **Broadcasting:**
   - Numpy's broadcasting mechanism allows for automatic shape inference and element-wise operations between arrays of different shapes.
   - This simplifies code and improves performance.

In [ ]:
import numpy as np

# Create a Python list
python_list = list(range(1000000))

# Create a Numpy array
numpy_array = np.array(python_list)

In [ ]:
def multiplication_for_loop(list):
    result = []
    for item in list:
        result.append(item * 2)
    return result

In [ ]:
# Element-wise multiplication in Python list using for loop
%timeit result_list = multiplication_for_loop(python_list)

163 ms ± 52 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
# Element-wise multiplication in Python list with list comprehension
%timeit result_list = [x * 2 for x in python_list]

52.1 ms ± 1.25 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
# Element-wise multiplication in Numpy array
%timeit result_array = numpy_array * 2

1.33 ms ± 112 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
